package interfaz;

public class ListahashtagfamososUsuarioRegistrado_item extends ListahashtagsgeneralUsuarioRegistrado_item {
	public ListahashtagfamososUsuarioRegistrado _listahashtagfamososUsuarioRegistrado;
}